config/routes.rb
# frozen_string_literal: true

Tramway::Admin::Engine.routes.draw do
  mount Tramway::Export::Engine, at: '/' if defined? Tramway::Export::Engine

  root to: 'welcome#index'

  resources :records
  resource :singleton, only: %i[new create show edit update]
  resources :has_and_belongs_to_many_records, only: %i[create destroy]
  resource :session, only: %i[new create]
  get 'sign_out', to: 'sessions#destroy'
end

app/views/tramway/admin/shared/show/associations/_habtm_row.html.haml
- if object.class.show_associations.map(&:to_s).include? association.name.to_s
  %tr
    %td
      = model_class.human_attribute_name association.name
      %hr
      - association_form = object.send("add_#{association.name}_form")
      = simple_form_for association_form, url: { controller: :has_and_belongs_to_many_records, action: :create, form: association_form.class, model_class: model_class, object_id: object.id }, method: :post do |f|
        - association_form.associations.each do |association_name|
          - associations = association_form.model.class.reflect_on_all_associations.map(&:name)
          - if associations.include? association_name
            = f.association association_name, label: false
            = f.button :submit, "#{I18n.t('helpers.actions.add')} #{model_class.human_attribute_name(association.name).singularize.downcase}", class: 'btn-success'
    %td{ colspan: 2 }
      = render 'tramway/admin/shared/show/associations/list', object: object, association: association

app/views/tramway/admin/shared/show/associations/_list.html.haml
- association_state_machines = object.send("#{association.name}_state_machines")
%table.table.table-striped.table-bordered
  - object.send(association.name)&.each do |association_object|
    %tr{ id: "#{association.name}_#{association_object.id}" }
      %td
        = association_object.id
      %td
        = link_to association_object.name, record_path(association_object.id, model: association.options[:class_name])
      %td
        - association_state_machines.each do |state_method|
          = state_events_buttons association_object, state_method: state_method, model_param_name: :record, controller: 'tramway/admin/records', action: :update, parameters: { redirect: current_model_record_path(object.id), model: association_object.class.model_name }, button_options: { class: :smart_button }
      %td
        - if update_is_available? association_object, object
          = edit_button url: edit_record_path(association_object.id, model: association.options[:class_name], redirect: current_model_record_path(object.id)), button_options: { class: 'btn btn-xs btn-warning edit' } do
            = fa_icon 'pencil-alt'
        - if destroy_is_available? association_object, object
          = delete_button url: record_path(association_object.id, model: association.options[:class_name], redirect: current_model_record_path(object.id)), button_options: { class: 'btn btn-xs btn-danger delete' } do
            = fa_icon 'trash-alt'
        - if habtm_destroy_is_available? association_object, object
          = delete_button url: has_and_belongs_to_many_record_path(association_object.id, model_class: object.model.class, object_id: object.id, form: "Admin::#{object.model.class.to_s.pluralize}::Remove#{association_object.model.class.to_s}Form", redirect: current_model_record_path(object.id)), button_options: { class: 'btn btn-xs btn-danger delete' } do
            = fa_icon 'trash-alt'

app/views/tramway/admin/shared/show/associations/_row.html.haml
- if object.class.show_associations.nil?
  = "Please, fill show associations method in decorator"
- else
  - if object.class.show_associations.map(&:to_s).include? association.name.to_s
    - association_type = association.class.to_s.split('::').last.sub(/Reflection$/, '').underscore.to_sym
    %tr
      %td
        = model_class.human_attribute_name association.name
        %hr
        - if create_is_available?(association.class_name) && (association_type != :has_one || !object.send(association.name).present?)
          = link_to "#{I18n.t('helpers.actions.add')} #{model_class.human_attribute_name(association.name).singularize.downcase}", new_associated_record_path(association: association, object: object, as: object.send("#{association.name}_as")), class: 'btn btn-primary'
      %td{ colspan: 2 }
        - if association_type.in? [ :has_one, :belongs_to ]
          %table.table.table-striped.table-bordered
            = render 'tramway/admin/shared/show/associations/table_row', object: object, association: association, association_object: object.send(association.name)
        - else
          %table.table.table-striped.table-bordered
            - object.send(association.name)&.each do |association_object|
              = render 'tramway/admin/shared/show/associations/table_row', object: object, association: association, association_object: association_object

app/views/tramway/admin/shared/show/associations/_table_row.html.haml
- if (!association_object.is_a?(Array) || !association_object.empty?) && association_object.present?
  %tr{ id: "#{association.name}_#{association_object.id}" }
    %td
      = association_object.id
    %td
      = link_to association_object.name, record_path(association_object.id, model: association.options[:class_name])
    - if association_object.model.class.state_machines_names.count > 1
      - state_machine_names = association_object.listed_state_machines || association_object.model.class.state_machines_names
      %td
        - state_machine_names.each do |state_method|
          - unless state_method == 'default'
            = state_events_buttons association_object, state_method: state_method, model_param_name: :record, controller: 'tramway/admin/records', action: :update, parameters: { redirect: current_model_record_path(object.id), model: association_object.class.model_name }, button_options: { class: :smart_button }
    %td{ style: 'display: flex; justify-content: space-evenly' }
      - if update_is_available? association_object, object
        = edit_button url: edit_record_path(association_object.id, model: association.options[:class_name], redirect: current_model_record_path(object.id)), button_options: { class: 'btn btn-xs btn-warning edit', style: 'height: max-content' } do
          = fa_icon 'pencil-alt'
      - if destroy_is_available? association_object, object
        = delete_button url: record_path(association_object.id, model: association.options[:class_name], redirect: current_model_record_path(object.id)), button_options: { class: 'btn btn-xs btn-danger delete' } do
          = fa_icon 'trash-alt'
      - if habtm_destroy_is_available? association_object, object
        = delete_button url: has_and_belongs_to_many_record_path(association_object.id, model_class: object.model.class, object_id: object.id, form: "Admin::#{object.model.class.to_s.pluralize}::Remove#{association_object.model.class.to_s}Form", redirect: current_model_record_path(object.id)), button_options: { class: 'btn btn-xs btn-danger delete' } do
          = fa_icon 'trash-alt'